# Site settings
title: Moax Wang
SEOTitle: Moax.Wang Blog
header-img: img/home-bg.jpg
email: moax.wang@outlook.com
description: "Moax Wang Personal Blog"
keyword: "Chemical, Engineering, DIY, Canada, Student, MOAX"
url: "https://moaxwang.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/MoaxWang/moaxwang.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Nothing more than a student."
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: true
github_username: MoaxWang
#linkedin_username: None

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Analytics settings
# Google Analytics
# ga_track_id: 'UA-99999999-9'            # Format: UA-xxxxxx-xx
# ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "Huxpro",
        href: "http://huangxuan.me/"
    },{
        title: "Qiubaiying",
        href: "https://qiubaiying.github.io/"
    },{
        title: "Duter2016",
        href: "https://duter2016.github.io"
    },{
        title: "Richardurben",
        href: "https://richardurben.github.io"
    }
]
