# Site settings
title: Winchell Wang
SEOTitle: Winchell.Wang Blog
header-img: img/home-bg.jpg
email: winchell.wang@outlook.com
description: "Winchell Wang Personal Blog"
keyword: "Winchell, winchell.wang, winchellwang, Winchell.Wang Blog, winchellwang blog, engineering"
url: "https://winchellwang.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/winchellwang/winchellwang.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "🇨🇳 🇦🇺 🇺🇸 🇨🇦<br>📷 <a href='http://pixelfed.social/moax'>pixelfed.social/moax</a>"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: true
github_username: WinchellWang
#linkedin_username: None

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 5
exclude: ["less","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# giscus
giscus:
    enable: true #是否开启giscus评论
    repo: WinchellWang/winchellwang.github.io #仓库名称
    repo-id: R_kgDOHnDuaQ #仓库ID
    category: General #评论默认类别
    category-id: DIC_kwDOHnDuac4CWMWd #分类ID

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID:                             #生成的clientID
  clientSecret:     #生成的clientSecret
  repo: winchellwang.github.io    #仓库名称
  owner: winchellwang    #github用户名
  admin: winchellwang
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Analytics settings
# Google Analytics
# ga_track_id: 'UA-99999999-9'            # Format: UA-xxxxxx-xx
# ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 2              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
      title: "Martin Thissen",
      href: "https://medium.com/@martin-thissen"
    },{
      title: "哲科文",
      href: "http://jerkwin.github.io"
    },{
      title: "Meta AI",
      href: "https://ai.facebook.com/results/?amp%3Bsort_by=most_recent&content_types%5B0%5D=publication"
    }
]
